/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UEWN5tZzHgj
 */
import Link from "next/link";
import { CardHeader, CardContent, Card } from "@/components/ui/card";

export function Contact() {
   return (
      <div className="font-grenze-gotisch text-white bg-gray-800 min-h-screen">
         <header className="flex items-center justify-between p-6 bg-gray-900 border-2 border-gray-700 shadow-md">
            <h1 className="text-4xl font-bold text-blue-500">My Blog</h1>
            <nav>
               <ul className="flex space-x-4">
                  <li>
                     <Link className="text-white hover:text-gray-300" href="#">
                        Home
                     </Link>
                  </li>
                  <li>
                     <Link className="text-white hover:text-gray-300" href="#">
                        About
                     </Link>
                  </li>
                  <li>
                     <Link className="text-white hover:text-gray-300" href="#">
                        Contact
                     </Link>
                  </li>
               </ul>
            </nav>
         </header>
         <main className="flex flex-col md:flex-row space-y-6 md:space-y-0 md:space-x-6 p-6">
            <section className="md:w-1/3">
               <div className="mb-6 border-2 border-gray-700 shadow-md bg-gray-900" />
            </section>
            <section className="md:w-1/3">
               <div className="mb-6 border-2 border-gray-700 shadow-md bg-gray-900">
                  <Card>
                     <CardHeader className="bg-blue-500 text-white">
                        <h2 className="text-3xl font-bold">Contact Me</h2>
                        <p>I'd love to hear from you!</p>
                     </CardHeader>
                     <CardContent>
                        <p className="mt-4">
                           Feel free to reach out to me via the following
                           methods:
                        </p>
                        <ul className="list-disc list-inside mt-4 text-gray-300">
                           <li>Email: myemail@example.com</li>
                           <li>Phone: (123) 456-7890</li>
                           <li>
                              LinkedIn:{" "}
                              <Link
                                 className="text-white hover:text-gray-300"
                                 href="#"
                              >
                                 My LinkedIn Profile
                              </Link>
                           </li>
                        </ul>
                     </CardContent>
                  </Card>
               </div>
            </section>
            <section className="md:w-1/3">
               <div className="mb-6 border-2 border-gray-700 shadow-md bg-gray-900" />
            </section>
         </main>
         <footer className="p-6 bg-gray-900 border-2 border-gray-700 mt-6">
            <p className="text-center text-white">© 2023 My Blog</p>
         </footer>
      </div>
   );
}
