/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gMHxDHiwqEd
 */
import Link from "next/link"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function landing() {
  return (
    <div className="font-mono text-black bg-gray-200 min-h-screen">
      <header className="flex items-center justify-between p-6 bg-white border-2 border-black shadow-md">
        <h1 className="text-3xl font-bold">My Blog</h1>
        <nav>
          <ul className="flex space-x-4">
            <li>
              <Link className="text-black hover:text-gray-700" href="#">
                Home
              </Link>
            </li>
            <li>
              <Link className="text-black hover:text-gray-700" href="#">
                About
              </Link>
            </li>
            <li>
              <Link className="text-black hover:text-gray-700" href="#">
                Contact
              </Link>
            </li>
          </ul>
        </nav>
      </header>
      <main className="flex flex-col md:flex-row space-y-6 md:space-y-0 md:space-x-6 p-6">
        <section className="md:w-full">
          <div className="mb-6 border-2 border-black shadow-md">
            <Card>
              <CardHeader>
                <h2 className="text-2xl font-bold">Welcome to My Blog!</h2>
                <p className="text-black">A place to share my thoughts and ideas.</p>
              </CardHeader>
              <CardContent>
                <img
                  alt="Landing image"
                  className="w-full h-auto"
                  height="400"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width="600"
                />
                <p className="mt-4">
                  Explore my latest posts, learn more about me, or get in touch. I'm glad you're here.
                </p>
                <Button className="bg-gray-300 hover:bg-gray-400 mt-4">
                  <Link href="#">Read Latest Post</Link>
                </Button>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
      <footer className="p-6 bg-white border-2 border-black mt-6">
        <p className="text-center text-black">© 2023 My Blog</p>
      </footer>
    </div>
  )
}
